### ISSUE TITLE
How to accomplish "Your name here" on a Sense2

### ISSUE THREAD

**Issue by Nytshaed** [morgosus/fitboy-sense#5]
Hello! I've downloaded your FitBoy watchface for my Fitbit Sense2.  How do I get my name in the "Your Name Here" area?  I've set up a display name in the Fitbit app.  Thanks for an awesome watch face!

**Comment by morgosus** [comment]
Application settings, tap on the watch face in your installed watch faces and the settings are somewhere down there.
